export const HEADER_STYLE_WHITE = 'HEADER_STYLE_WHITE';
export const HEADER_STYLE_RELATIVE = 'HEADER_STYLE_RELATIVE';
export const HEADER_STYLE_OPACITY = 'HEADER_STYLE_OPACITY';
export const SCROLLED = 'SCROLLED';
export const HEADER_CART_STATUS = 'HEADER_CART_STATUS';